# Generated by Django 3.0.1 on 2019-12-27 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('calorias', models.IntegerField(default=0, verbose_name='Calorias')),
            ],
        ),
        migrations.CreateModel(
            name='Masa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio')),
                ('ingredientes', models.ManyToManyField(to='appMammaMiaDef.Ingrediente')),
                ('masa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMammaMiaDef.Masa')),
            ],
        ),
    ]
