# Generated by Django 3.0.1 on 2019-12-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('telefono', models.CharField(max_length=40, verbose_name='Telefono')),
            ],
        ),
    ]
